vokal = str(input())
A = vokal.count("a")
I = vokal.count("i")
U = vokal.count("u")
E = vokal.count("e")
O = vokal.count("o")
aa = vokal.count("A")
bb = vokal.count("I")
cc = vokal.count("U")
dd = vokal.count("E")
ee = vokal.count("O")
print(int(A+I+U+E+O+aa+bb+cc+dd+ee))